### ISSUE TITLE
Inference time, and implementation of NeuS/Instant-NeuS

### ISSUE THREAD

**Issue by fatbao55** [3D-FRONT-FUTURE/NeuDA#3]
Thanks for the great work! I have 2 questions:

1. What is the inference time of the method compared to NeuS and Instant-NeuS? Since your paper mentions that `NeuDA converges rapidly and yields the lowest value compared to NeuS and Instant-NeuS, which means NeuDA can produce more clear and sharper surfaces with less time cost`. 

2. You compared to NeuS and Instant-NeuS in the paper. Do you mind sharing your implementation of those code?

Hope to hear from you soon, thank you!

**Comment by BwCai** [comment]
Sorry for the late reply. 
NeuDA is faster than NeuS since it employs shallow MLPs (4 vs. 8 for NeuS), while its inference time is similar to Instant-NeuS. In addition, our experiments found that NeuDA achieves a better surface reconstruction than NeuS and Instant-NeuS with the same training iterations.

We use the original [NeuS](https://github.com/Totoro97/NeuS) code in our experiments. For the Instant-NeuS, we replace the position encoding with hash encoding and leverage shallow (4-layers) MLPs to construct an SDF network that is easy to reproduce. Moreover, there are currently many excellent open-source repos you can refer to, e.g. [Instant-nsr-pl](https://github.com/bennyguo/instant-nsr-pl), [torch-ngp](https://github.com/ashawkey/torch-ngp), [instant-ngp](https://github.com/NVlabs/instant-ngp).

**Comment by fatbao55** [comment]
Thanks for the clarification!
