### ISSUE TITLE
About Training time

### ISSUE THREAD

**Issue by yec22** [3D-FRONT-FUTURE/NeuDA#4]
Hi, thanks for your great job!

I run the code on an NVIDIA A100 GPU (following neuda_wmask.conf), and the complete training time cost ~5 hours, which is similar to NeuS. This confuses me. As NeuDA leverages hash-table as instant-NGP, shouldn't NeuDA converges faster than NeuS?

Looking forward to you reply!!!

**Comment by BwCai** [comment]
Thanks for your interest. 
We tested NeuDA on the Nvidia V100 GPU, NeuDA is a bit faster than NeuS. NeuDA has a less time cost on each iteration since it employs a shallower MLP (4 vs. 8 for NeuS). Besides, NeuDA leverages deformable anchor grids instead of hash grids to achieve better convergence. 
But NeuDA is slower than Instant-NGP in this implementation because there are some accelerated strategies (such as occupancy grids and fully fused MLPs) used in Instant-NGP not implemented in this repo.
