### ISSUE TITLE
extract mesh error

### ISSUE THREAD

**Issue by Yingminj** [3D-FRONT-FUTURE/NeuDA#7]
Thank you for your contribution！
I have a problem when running this code but I have output_mesh.ply, is there any way to fix this problem?
I did not find the setting for this path in config(data/dtu_eval/ObsMask/ObsMask97_10.mat)
![2023-10-13 22-13-45屏幕截图](https://github.com/3D-FRONT-FUTURE/NeuDA/assets/144242264/8a6da6da-a26b-43b0-bbce-035be53c6310)

**Comment by BwCai** [comment]
Thanks for your interest. The observability mask (e.g. `ObsMask**.mat`) is used to evaluate the reconstructed mesh, which is provided in the [DTU Point Clouds](http://roboimagedata.compute.dtu.dk/?page_id=36). For the evaluation, you need to download both [`SampleSet`](http://roboimagedata2.compute.dtu.dk/data/MVS/SampleSet.zip) and [`Points`](http://roboimagedata2.compute.dtu.dk/data/MVS/Points.zip).

**Comment by Yingminj** [comment]
Thank you for your reply.
I also encountered some problems. When I use custom data, the mesh effect is not ideal. Have you encountered this before?
When I add mask, the effect is almost the same

**Comment by Yingminj** [comment]
![2023-10-15 21-54-49 的屏幕截图](https://github.com/3D-FRONT-FUTURE/NeuDA/assets/144242264/c62a5401-6c54-44ca-b679-47cab64873a6)
![frame_15](https://github.com/3D-FRONT-FUTURE/NeuDA/assets/144242264/c9acd4cf-b757-4889-8a7d-8c6caa5d92ef)

**Comment by BwCai** [comment]
The quality of reconstructed mesh relies on the correct estimation of the camera parameters.  So checking the camera parameters may help you figure out what the problem is. Some tools, [colmap gui](https://colmap.github.io/gui.html), [visualize cameras in 3D](https://github.com/Kai-46/nerfplusplus#visualize-cameras-in-3d), can be used to visualize the camera pose for checking.
